update wallpaper script

diff --git a/private_dot_local/bin/executable_wallpaper b/private_dot_local/bin/executable_wallpaper
--- a/private_dot_local/bin/executable_wallpaper
+++ b/private_dot_local/bin/executable_wallpaper
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 function error() {
-    echo -e "\033[0;31mError:\033[0m $1"
+    echo -e "\033[0;31mError:\033[0m $1" 1>&2
 }
 
 function kill_swaybg() {
@@ -15,8 +15,7 @@ if [[ ! -f $config ]]; then
     exit 1
 fi
 
-cmd="$1"
-shift
+cmd="$1" ; shift
 
 case "$cmd" in
     "restore")
@@ -27,10 +26,12 @@ case "$cmd" in
     "set")
         path="$1"
         
-        if [[ -z $path ]]; then
+        if [[ ! -f $path ]] && [[ ! $(file --mime-type -b "$path") =~ image/* ]]; then
             error "invalid path '$path'"
             exit 1
         fi
+
+        path="$(realpath "$path")"
 
         kill_swaybg
         swaybg -o '*' -m fill -i "$path" &
